name: OpenPorts
options:
  bundleIdPrefix: com.openports
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  OpenPorts:
    type: application
    platform: macOS
    sources:
      - path: OpenPorts
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.openports.app
        PRODUCT_NAME: OpenPorts
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        # Menu bar app settings (no dock icon)
        INFOPLIST_KEY_LSUIElement: YES
        # App category
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        # Disable app sandbox to allow shell commands
        CODE_SIGN_ENTITLEMENTS: ""
        ENABLE_APP_SANDBOX: NO
        # Development signing
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
